on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-11-arm
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup visual studio
        uses: microsoft/setup-msbuild@v2

      - name: Install winget and LLVM
        shell: pwsh
        run: |
          .\scripts\install_winget.ps1
          winget install --id LLVM.LLVM --version "20.1.0"

      - name: Test shell
        run: |
          get-command clang
          get-command flang
