on:
  push:
    branches:
      - main

env:
  MSYS_ROOT: c:\msys64

jobs:
  build:
    runs-on: windows-11-arm
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup visual studio
        uses: microsoft/setup-msbuild@v2

      - name: Install winget
        # We need "powershell" to downgrade from powershell 7, because of:
        # https://github.com/PowerShell/PowerShell/issues/18708
        shell: powershell
        run: |
          .\scripts\install_winget.ps1

      - name: Install MSYS2
        run: |
          winget install --id=MSYS2.MSYS2 -e --accept-source-agreements --accept-package-agreements
          cd $env:MSYS_ROOT
          .\clangarm64.exe | Out-Null
          .\usr\bin\pacman -Suy --noconfirm
          .\usr\bin\pacman.exe -S mingw-w64-clang-aarch64-cmake --noconfirm
          # mingw-w64-clang-aarch64-flang
          # mingw-w64-clang-aarch64-clang

      - name: Add msys arm64 stuff to front of PATH
        run: |
          # https://stackoverflow.com/a/39628224
          @("$env:MSYS_ROOT\clangarm64\bin") + (get-content $env:GITHUB_PATH) | set-content $env:GITHUB_PATH

      - name: Install LLVM
        run: |
          winget install --id LLVM.LLVM --version "20.1.0" --accept-source-agreements --accept-package-agreements --silent

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: error_logs
          path: "*.log"

      - name: Test shell
        run: |
          get-command clang
          get-command flang
          get-command cmake
