on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-11-arm
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup visual studio
        uses: microsoft/setup-msbuild@v2

      - name: Install winget
        run: |
          # https://github.com/asheroto/winget-install
          Install-Script winget-install -Force
          winget-install

      - name: Test winget
        run:
          winget search LLVM

      - name: Install LLVM
        run:
          winget install --id=LLVM.LLVM -e

      - name: Test shell
        run: |
          get-command cl
