on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-11-arm
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup visual studio
        uses: microsoft/setup-msbuild@v2

      - name: Install scoop (Windows)
        uses: winpax/scoop-setup@v1.0.0

      - name: Install LLVM
        run:
          scoop install main/llvm

      - name: Test shell
        run: |
          get-command clang
