on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-11-arm
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup visual studio
        uses: microsoft/setup-msbuild@v2

      - name: Install winget
        # We need "powershell" to downgrade from powershell 7, because of:
        # https://github.com/PowerShell/PowerShell/issues/18708
        shell: powershell
        run: |
          .\scripts\install_winget.ps1

      - name: Install LLVM
        run: |
          winget install --id LLVM.LLVM --version "20.1.0" --accept-source-agreements --accept-package-agreements --silent

      - name: Install CMake
        run: |
          winget install cmake --force --accept-source-agreements --accept-package-agreements --verbose

      - name: Test shell
        run: |
          get-command clang
          get-command flang
          get-command cmake

      - uses: actions/upload-artifact@v4.3.0
        with:
          if: failure()
          name: error_logs
          path: $HOME\AppData\Local\Packages
